// Built-in word categories. Custom categories live in storage.js.

export const BUILTIN_CATEGORIES = [
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🐾',
    words: [
      'Elephant', 'Kangaroo', 'Penguin', 'Octopus', 'Giraffe', 'Hedgehog',
      'Dolphin', 'Flamingo', 'Chameleon', 'Sloth', 'Platypus', 'Raccoon',
      'Peacock', 'Jellyfish', 'Armadillo', 'Meerkat', 'Walrus', 'Toucan',
      'Lobster', 'Gorilla', 'Hamster', 'Ostrich', 'Seahorse', 'Porcupine',
      'Panther', 'Beaver', 'Falcon', 'Iguana', 'Moose', 'Squid',
      'Tarantula', 'Pelican', 'Otter', 'Cobra', 'Bison', 'Ferret',
      'Koala', 'Vulture', 'Newt', 'Mongoose',
      'Cheetah', 'Panda', 'Owl', 'Crocodile', 'Bat', 'Skunk', 'Scorpion', 'Woodpecker', 'Llama', 'Starfish',
      'Tiger', 'Lion', 'Zebra', 'Rhinoceros', 'Hippopotamus', 'Leopard',
      'Hyena', 'Wolf', 'Fox', 'Polar Bear', 'Grizzly Bear', 'Reindeer',
      'Camel', 'Donkey', 'Goat', 'Sheep', 'Alpaca', 'Chimpanzee',
      'Orangutan', 'Baboon', 'Lemur', 'Kookaburra', 'Parrot', 'Swan',
      'Goose', 'Rooster', 'Turkey', 'Eagle', 'Hawk', 'Puffin', 'Stingray',
      'Shark', 'Whale', 'Swordfish', 'Pufferfish', 'Crab', 'Shrimp',
      'Snail', 'Earthworm', 'Grasshopper', 'Praying Mantis', 'Butterfly',
      'Dragonfly', 'Ladybug', 'Cockroach', 'Alligator', 'Tortoise',
      'Salamander', 'Frog', 'Rabbit',
    ],
  },
  {
    id: 'movies',
    name: 'Movies & TV',
    emoji: '🎬',
    words: [
      'Titanic', 'Jurassic Park', 'The Lion King', 'Star Wars', 'Frozen',
      'Harry Potter', 'Spider-Man', 'Finding Nemo', 'The Matrix', 'Shrek',
      'Batman', 'Toy Story', 'Indiana Jones', 'Pirates of the Caribbean',
      'The Avengers', 'Ghostbusters', 'Jaws', 'E.T.', 'Rocky', 'Godzilla',
      'King Kong', 'The Wizard of Oz', 'Forrest Gump', 'Home Alone',
      'Back to the Future', 'The Terminator', 'Aladdin', 'Mary Poppins',
      'Stranger Things', 'Game of Thrones', 'The Office', 'Friends',
      'SpongeBob', 'The Simpsons', 'Sherlock Holmes', 'James Bond',
      'Mission Impossible', 'Kung Fu Panda', 'Despicable Me', 'Squid Game',
      'The Godfather', 'Avatar', 'Inception', 'Breaking Bad', 'Pokémon', 'Scooby-Doo', 'Barbie', 'Top Gun', 'The Hunger Games', 'Moana',
      'The Lord of the Rings', 'Black Panther', 'Iron Man', 'Wonder Woman',
      'Superman', 'Deadpool', 'Guardians of the Galaxy', 'Inside Out',
      'The Incredibles', 'Monsters Inc.', 'Ratatouille', 'Coco', 'Mulan',
      'Beauty and the Beast', 'The Little Mermaid', 'Peter Pan',
      'Willy Wonka', 'The Karate Kid', 'Men in Black', 'Cast Away',
      'The Mummy', 'Planet of the Apes', 'Night at the Museum', 'Cars',
      'Up', 'Encanto', 'Brave', 'How to Train Your Dragon', 'Madagascar',
      'The Walking Dead', 'Wednesday', 'The Mandalorian', 'Doctor Who',
      'Star Trek', 'Grey\'s Anatomy', 'Modern Family', 'Brooklyn Nine-Nine',
      'The Big Bang Theory', 'South Park', 'Sesame Street', 'Tom and Jerry',
      'Paw Patrol', 'Teenage Mutant Ninja Turtles', 'Power Rangers',
      'Transformers', 'The X-Files', 'Baywatch', 'Mr. Bean', 'Cinderella',
      'Alice in Wonderland',
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emoji: '🍕',
    words: [
      'Pizza', 'Spaghetti', 'Sushi', 'Pancakes', 'Burrito', 'Popcorn',
      'Ice Cream', 'Hot Dog', 'Cheeseburger', 'Ramen', 'Croissant',
      'Guacamole', 'Waffles', 'Lasagna', 'Milkshake', 'Doughnut',
      'French Fries', 'Cotton Candy', 'Meatballs', 'Nachos', 'Omelette',
      'Cupcake', 'Lemonade', 'Bubble Tea', 'Fried Chicken', 'Bagel',
      'Corn on the Cob', 'Cheesecake', 'Espresso', 'Smoothie', 'Pretzel',
      'Dumplings', 'Watermelon', 'Barbecue Ribs', 'Garlic Bread', 'Taco',
      'Pumpkin Pie', 'Scrambled Eggs', 'Churros', 'Marshmallow',
      'Avocado Toast', 'Mac and Cheese', 'Onion Rings', 'Pad Thai', 'Caesar Salad', 'Hot Chocolate', 'Apple Pie', 'Falafel', 'Sausage Roll', 'Chicken Nuggets',
      'Grilled Cheese', 'Tomato Soup', 'Mashed Potatoes', 'Club Sandwich',
      'Fish and Chips', 'Fried Rice', 'Spring Rolls', 'Curry', 'Kebab',
      'Paella', 'Risotto', 'Gnocchi', 'Ravioli', 'Tortellini', 'Baked Potato',
      'Chicken Wings', 'Steak', 'Roast Turkey', 'Clam Chowder', 'Tuna Salad',
      'Coleslaw', 'Potato Salad', 'Porridge', 'Cereal', 'French Toast',
      'Hash Browns', 'Bacon', 'Boiled Egg', 'Chocolate Cake', 'Brownie',
      'Cinnamon Roll', 'Banana Split', 'Fruit Salad', 'Mango', 'Pineapple',
      'Strawberry', 'Coconut', 'Peanut Butter', 'Jelly Beans',
      'Gingerbread Man', 'Fortune Cookie', 'Chocolate Bar', 'Iced Coffee',
      'Green Tea', 'Orange Juice', 'Root Beer', 'Coconut Water',
      'Sparkling Water', 'Milk', 'Cherry Pie',
    ],
  },
  {
    id: 'sports',
    name: 'Sports & Games',
    emoji: '⚽',
    words: [
      'Basketball', 'Surfing', 'Bowling', 'Archery', 'Fencing', 'Karate',
      'Gymnastics', 'Skateboarding', 'Volleyball', 'Ping Pong', 'Golf',
      'Ice Skating', 'Rock Climbing', 'Sumo Wrestling', 'Baseball',
      'Cheerleading', 'Darts', 'Curling', 'Javelin', 'Marathon',
      'Pole Vault', 'Synchronized Swimming', 'Tug of War', 'Yoga',
      'Hopscotch', 'Limbo', 'Musical Chairs', 'Hide and Seek', 'Chess',
      'Poker', 'Billiards', 'Badminton', 'Kayaking', 'Zumba', 'Boxing',
      'Snowboarding', 'Juggling', 'Arm Wrestling', 'Dodgeball', 'Frisbee',
      'Foosball', 'Cricket', 'Rugby', 'Handball', 'Skydiving', 'Water Polo', 'Hula Hoop', 'Jenga', 'Paintball', 'Laser Tag',
      'Soccer', 'Tennis', 'Swimming', 'Running', 'Cycling', 'Wrestling',
      'Weightlifting', 'Hockey', 'Skiing', 'Sailing', 'Rowing', 'Canoeing',
      'Horse Racing', 'Table Football', 'Snooker', 'Mini Golf', 'Softball',
      'Kickball', 'Lacrosse', 'Squash', 'Racquetball', 'Roller Skating',
      'Bungee Jumping', 'Hang Gliding', 'Scuba Diving', 'Snorkeling',
      'Water Skiing', 'Windsurfing', 'Mountain Biking', 'Paddleboarding',
      'Trampolining', 'High Jump', 'Long Jump', 'Shot Put', 'Discus Throw',
      'Relay Race', 'Triathlon', 'Hurdles', 'Figure Skating', 'Ballet',
      'Capture the Flag', 'Tag', 'Checkers', 'Dominoes', 'Charades',
      'Bingo', 'Tic-Tac-Toe', 'Rock Paper Scissors', 'Cornhole',
      'Whack-a-Mole',
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs & People',
    emoji: '🧑‍🚒',
    words: [
      'Firefighter', 'Astronaut', 'Magician', 'Dentist', 'Plumber',
      'Ballerina', 'Ninja', 'Pirate', 'Chef', 'Lifeguard', 'Detective',
      'Barber', 'Clown', 'Opera Singer', 'Weather Reporter', 'Referee',
      'Mime', 'Librarian', 'Tattoo Artist', 'Cowboy', 'Judge', 'Paparazzi',
      'Fortune Teller', 'Bodyguard', 'Zookeeper', 'Mail Carrier',
      'Flight Attendant', 'Archaeologist', 'DJ', 'Beekeeper', 'Butler',
      'Cheerleader', 'Electrician', 'Fisherman', 'Knight', 'Mermaid',
      'Photographer', 'Santa Claus', 'Scientist', 'Vampire',
      'Pilot', 'Nurse', 'Farmer', 'Waiter', 'Superhero', 'Robot', 'Wizard', 'Ghost', 'Pop Star', 'Teacher',
      'Doctor', 'Veterinarian', 'Police Officer', 'Paramedic', 'Mechanic',
      'Carpenter', 'Painter', 'Architect', 'Engineer', 'Programmer',
      'Cashier', 'Baker', 'Gardener', 'Janitor', 'Bus Driver', 'Taxi Driver',
      'Train Conductor', 'News Anchor', 'Tour Guide', 'Personal Trainer',
      'Therapist', 'Lawyer', 'Accountant', 'Real Estate Agent', 'Musician',
      'Drummer', 'Guitarist', 'Actor', 'Film Director', 'Fashion Designer',
      'Model', 'Dancer', 'Circus Ringmaster', 'Stunt Performer', 'Spy',
      'Royal Guard', 'Queen', 'King', 'Prince', 'Princess', 'Monk',
      'Sailor', 'Soldier', 'Explorer', 'Inventor', 'News Photographer',
      'Dog Walker', 'Delivery Driver', 'Street Performer', 'Tourist',
    ],
  },
  {
    id: 'objects',
    name: 'Everyday Objects',
    emoji: '🧰',
    words: [
      'Umbrella', 'Toothbrush', 'Microwave', 'Stapler', 'Flashlight',
      'Vacuum Cleaner', 'Sunglasses', 'Backpack', 'Alarm Clock', 'Scissors',
      'Hairdryer', 'Ladder', 'Telescope', 'Wheelbarrow', 'Ironing Board',
      'Fire Extinguisher', 'Rubber Duck', 'Piggy Bank', 'Trampoline',
      'Boomerang', 'Compass', 'Lawnmower', 'Blender', 'Candle', 'Doorbell',
      'Fishing Rod', 'Hammock', 'Kite', 'Magnet', 'Mousetrap', 'Padlock',
      'Remote Control', 'Rolling Pin', 'Seatbelt', 'Shopping Cart',
      'Snow Globe', 'Swiss Army Knife', 'Typewriter', 'Water Balloon',
      'Zipper',
      'Binoculars', 'Wheelchair', 'Toaster', 'Stethoscope', 'Paperclip', 'Dustpan', 'Corkscrew', 'Bubble Wrap', 'Extension Cord', 'Garden Hose',
      'Coffee Mug', 'Frying Pan', 'Teapot', 'Whisk', 'Spatula', 'Chopsticks',
      'Can Opener', 'Lunchbox', 'Thermos', 'Cutting Board', 'Dishwasher',
      'Refrigerator', 'Ceiling Fan', 'Light Switch', 'Coat Hanger',
      'Laundry Basket', 'Clothes Iron', 'Sewing Machine', 'Safety Pin',
      'Measuring Tape', 'Hammer', 'Screwdriver', 'Wrench', 'Drill',
      'Paintbrush', 'Rake', 'Shovel', 'Sprinkler', 'Mailbox', 'Doormat',
      'Keychain', 'Wallet', 'Briefcase', 'Suitcase', 'Passport', 'Headphones',
      'Computer Mouse', 'Keyboard', 'Calculator', 'Camera', 'Tripod',
      'Megaphone', 'Microphone', 'Guitar', 'Drum', 'Skateboard', 'Bicycle',
      'Helmet', 'Traffic Cone', 'Stopwatch',
    ],
  },
  {
    id: 'actions',
    name: 'Actions',
    emoji: '🏃',
    words: [
      'Sneezing', 'Moonwalking', 'Shoveling Snow', 'Milking a Cow',
      'Walking a Dog', 'Changing a Tire', 'Baking a Cake', 'Sleepwalking',
      'Riding a Rollercoaster', 'Building a Sandcastle', 'Blowing Bubbles',
      'Brushing Teeth', 'Catching a Fish', 'Climbing a Tree',
      'Directing Traffic', 'Doing Laundry', 'Flying a Kite',
      'Getting a Haircut', 'Ice Fishing', 'Jump Rope', 'Karaoke',
      'Making a Snow Angel', 'Mowing the Lawn', 'Opening a Gift',
      'Painting a Fence', 'Parallel Parking', 'Playing Air Guitar',
      'Popping Popcorn', 'Proposing', 'Riding a Unicycle',
      'Rocking a Baby', 'Slipping on a Banana', 'Taking a Selfie',
      'Tightrope Walking', 'Tying Shoelaces', 'Waking Up Late',
      'Washing Dishes', 'Whistling', 'Wrapping a Present', 'Yawning',
      'Snoring', 'Hitchhiking', 'Skipping Stones', 'Watering Plants', 'Blowing Out Candles', 'Cracking an Egg', 'Digging a Hole', 'Painting Nails', 'Sharpening a Pencil', 'Swatting a Fly',
      'Peeling a Banana', 'Squeezing a Lemon', 'Flipping a Pancake',
      'Chopping Vegetables', 'Kneading Dough', 'Eating Spaghetti',
      'Drinking Hot Tea', 'Feeding a Baby', 'Walking on Stilts',
      'Riding a Horse', 'Paddling a Canoe', 'Rowing a Boat', 'Surfing a Wave',
      'Diving into a Pool', 'Climbing a Ladder', 'Crossing a Tightrope',
      'Lifting Weights', 'Doing Push-Ups', 'Running a Marathon',
      'Bowling a Strike', 'Shooting a Basketball', 'Swinging a Baseball Bat',
      'Serving a Tennis Ball', 'Playing the Drums', 'Conducting an Orchestra',
      'Playing the Violin', 'Taking a Photograph', 'Reading a Newspaper',
      'Writing a Letter', 'Typing on a Keyboard', 'Answering the Phone',
      'Knocking on a Door', 'Unlocking a Padlock', 'Hanging a Picture',
      'Fixing a Leaky Faucet', 'Hammering a Nail', 'Sawing Wood',
      'Raking Leaves', 'Planting a Tree', 'Picking Flowers', 'Walking in Rain',
      'Putting on Makeup', 'Combing Hair', 'Shaving a Beard',
      'Trying on Shoes', 'Packing a Suitcase', 'Checking the Time',
      'Searching for Keys', 'Waving Goodbye', 'Celebrating a Victory',
    ],
  },
  {
    id: 'places',
    name: 'Places',
    emoji: '🗺️',
    words: [
      'Eiffel Tower', 'Beach', 'Haunted House', 'Library', 'Volcano',
      'Desert Island', 'Amusement Park', 'North Pole', 'Pyramid', 'Jungle',
      'Space Station', 'Submarine', 'Castle', 'Farm', 'Airport',
      'Movie Theater', 'Dentist Office', 'Gas Station', 'Grand Canyon',
      'Great Wall of China', 'Gym', 'Hair Salon', 'Hospital', 'Hotel',
      'Laundromat', 'Lighthouse', 'Museum', 'Niagara Falls', 'Playground',
      'Post Office', 'Restaurant', 'School Bus', 'Shopping Mall',
      'Ski Resort', 'Statue of Liberty', 'Subway', 'Supermarket',
      'Treehouse', 'Waterpark', 'Zoo',
      'Bakery', 'Cave', 'Circus', 'Cruise Ship', 'Swamp', 'Football Stadium', 'Igloo', 'Prison', 'Rooftop', 'Windmill',
      'Aquarium', 'Art Gallery', 'Bank', 'Barbershop', 'Bowling Alley',
      'Bus Stop', 'Campsite', 'Cathedral', 'Coffee Shop', 'Construction Site',
      'Courthouse', 'Fire Station', 'Flower Shop', 'Forest', 'Golf Course',
      'Harbor', 'Ice Rink', 'Laboratory', 'Marketplace', 'Observatory',
      'Opera House', 'Parking Garage', 'Pharmacy', 'Police Station',
      'Railroad Station', 'Recording Studio', 'Recycling Center',
      'Skate Park', 'Swimming Pool', 'Theme Park', 'University', 'Vineyard',
      'Waterfall', 'Ancient Ruins', 'Bamboo Forest', 'Coral Reef',
      'Mountain Cabin', 'Rainforest', 'Safari Park', 'Secret Passage',
      'Toy Store', 'Candy Shop', 'Pet Store', 'Bookstore', 'Campground',
      'Greenhouse', 'Space Museum', 'Town Square', 'Clock Tower',
      'Underwater Cave',
    ],
  },
];

export function categoryById(id, customCategories = []) {
  return (
    BUILTIN_CATEGORIES.find((c) => c.id === id) ||
    customCategories.find((c) => c.id === id) ||
    null
  );
}

export function buildWordPool(categoryIds, customCategories = []) {
  const pool = [];
  for (const id of categoryIds) {
    const cat = categoryById(id, customCategories);
    if (cat) pool.push(...cat.words);
  }
  return [...new Set(pool)];
}
